### ISSUE TITLE
Escaping (ampersand) in browsable API URLs.

### ISSUE THREAD

**Issue by danielnaab** [tomchristie/django-rest-framework#1649]
When URLs with an escaped character (specifically in my case, and ampersand) is rendered in the browsable API, in the href it is improperly unescaped.  This may only apply to ampersands.

For example, this URL:
http://localhost:8000/endpoint/?param1=Yes+%26+No&param2=something

Would be rendered as:
http://localhost:8000/endpoint/?param1=Yes+&+No&param2=something

The URL is rendered in the value of the a element correctly... this only applies to the href.

**Comment by xordoquy** [comment]
I wonder whether it's possible to pull the failing test case from #2014

**Comment by tomchristie** [comment]
This comment https://github.com/tomchristie/django-rest-framework/pull/2014#issuecomment-61525348 implies that that issue was fixed in upstream Django. Closing this, but will reopen if anyone confirms it remains an issue.

**Comment by gabn88** [comment]
I just want to confirm it is working now :)

Love this library, it's already working great, but even then still getting better! 👍

**Comment by modernNeo** [comment]
I think this issue has returned? I am using 
```txt
Django==3.2.20
djangorestframework==3.14.0
```

and I am seeing this load for the `next` url
```html
<a href="http://127.0.0.1:8000/user_points/?page=2%C3%97tamp%3D5" rel="nofollow"><span class="str">http://127.0.0.1:8000/user_points/?page=2&amp;timestamp=5</span></a>
```
