### ISSUE TITLE
Re-add conditional abstract setting to Token model

### ISSUE THREAD

**Issue by adam-thomas** [tomchristie/django-rest-framework#3858]
When attempting to use [a custom model](https://github.com/incuna/django-user-management/blob/master/user_management/api/models.py#L42) instead of DRF's built-in `Token`, Django tries very hard to include the `Token` model even if `rest_framework.authtoken` isn't in `INSTALLED_APPS`.  Attempting to run migrations on a fresh database will explode with a missing user model error, and an already-set-up database will have a `Token` table added to it (which also means the user model gets an unwanted `auth_token` `OneToOne` field on it).

I believe a simple fix for this behaviour is to reinstate [the `Meta` `abstract` setting](https://github.com/tomchristie/django-rest-framework/blob/af0ea8ef5136da30cb058b10a493d36619d24add/rest_framework/authtoken/models.py#L24-L30) in the `Token` model.  I spent a day or so digging for other ways to avoid using `Token` in the project I was working on and couldn't find anything, but there may also be other fixes.

**Comment by xordoquy** [comment]
Should be fixed by #3785

**Comment by adam-thomas** [comment]
Unfortunately, that's the exact commit that introduces the breakage.  The delayed import doesn't seem to help.  I haven't been able to figure out why.

**Comment by adam-thomas** [comment]
When I was experimenting and trying to figure out how to work around this, I even deleted the entire `TokenAuthentication` class, and the problem persisted.  I think the `Token` model is being picked up through other means.

**Comment by adam-thomas** [comment]
(We're on Django 1.8.)

**Comment by xordoquy** [comment]
Do you have some sample project to reproduce the issue ?

**Comment by adam-thomas** [comment]
Not at the moment (it's a private project).  I'll try to get some time to make one.  I imagine it would involve:

- `rest_framework` in `INSTALLED_APPS` (but not `rest_framework.authtoken`)
- A `User` model exists and `AUTH_USER_MODEL` is set
- A test calls `_meta.get_all_field_names()` on that user model

I don't know if the migration ordering issue will occur for the test project - it depends on whether `Token` is migrated before `User`.  If it does, trying to run the tests will blow up with the SQL error about a missing relation.  If that error doesn't appear, the test should show that `auth_token` is a field on the `User` model.

**Comment by xordoquy** [comment]
Now that I read this again, I think I get the issue and indeed the Token should be left abstract if the app isn't in the INSTALLED_APPS.

**Comment by adam-thomas** [comment]
:+1: Thanks :)

**Comment by jpadilla** [comment]
@xordoquy so we keep #3785 and just revert the changes to the `Meta` class on the model?

**Comment by xordoquy** [comment]
Yup, that's #3860

**Comment by xordoquy** [comment]
@adam-thomas thanks for pointing this to our attention.

**Comment by adam-thomas** [comment]
Thank you @xordoquy :)

**Comment by adam-thomas** [comment]
And, most welcome!  Glad to help!

**Comment by tomchristie** [comment]
:+1:
